"""Utility stuff like database connection and layout"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['db', 'footer', 'links', 'post_tbl', 'thread_tbl', 'status_opts', 'layout', 'Post', 'Thread', 'Todo']

# %% ../nbs/utils.ipynb
from fasthtml.common import *
from monsterui.all import *
from fasthtml.components import Uk_theme_switcher


# %% ../nbs/utils.ipynb
db = Database('productivity_app.db')

# %% ../nbs/utils.ipynb
footer = Section(
        DivCentered(
            H2("Get in Touch", cls=(TextT.center, TextT.lg, TextT.bold)),
            Subtitle("Let's connect and collaborate!", cls='mb-6'),
            Address(
                DivHStacked(
                    A(DivLAligned(UkIcon('github', cls='mr-2'), "GitHub"),
                      href="https://github.com/isaac-flath",
                      cls=(AT.primary, 'hover:opacity-80')),
                    A(DivLAligned(UkIcon('linkedin', cls='mr-2'), "LinkedIn"),
                      href="https://linkedin.com/in/isaacflath",
                      cls=(AT.primary, 'hover:opacity-80')),
                    A(DivLAligned(UkIcon('twitter', cls='mr-2'), "Twitter"),
                      href="https://x.com/isaac_flath",
                      cls=(AT.primary, 'hover:opacity-80')),
                    cls='space-x-8')),
            cls='space-y-4'),
        cls=(SectionT.muted, 'py-12 mt-12')),

# %% ../nbs/utils.ipynb
links = (A('Home',href='/'),
         A("Theme"),DropDownNavContainer(Div(ThemePicker(), cls='p-6 uk-drop-close'), cls='w-96'),
         A('Blog', href='/blog'),
         A('Social', href='/social_media'))

# %% ../nbs/utils.ipynb
def layout(content, req):
    return Div(
        NavBar(*links, brand=H1("Isaac's Website", cls="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 via-green-500 to-indigo-400")),
        Container(content, cls=ContainerT.lg),
        footer)

# %% ../nbs/utils.ipynb
@dataclass
class Post:
    id: str # Post Id (pid) is PK
    tid: int # Thread ID (tid)
    position: int # position in thread
    content: str # text content
    img_path: str = None # fpath to image is used
    username: str = "User" # For UI - no functional purpose
    handle: str = "@user" # For UI - no functional purpose
    created_at: str = "Just now" # For UI - no functional purpose
    modified_at: str = None # TODO: add mofified timestampe
        

# %% ../nbs/utils.ipynb
@dataclass
class Thread:
    id: str # tid
    name: str # human readable name
    user: str # user this is for, used for filtering down what is shown in UI
    created_on: str=None # TODO: Add created date for UI selection/sorting

# %% ../nbs/utils.ipynb
post_tbl = db.create(Post, 'posts')
thread_tbl = db.create(Thread, 'threads')

# %% ../nbs/utils.ipynb
status_opts = ("Todo", "In Progress", "Done", "Archived", "Someday", "Other")

# %% ../nbs/utils.ipynb
class Todo:
    title: str; id: int; updated_at: str; labels: str; repo_url: str; 
    html_url: str; repo_owner: str; repo_name: str; number: int;
    status: str 

# %% ../nbs/utils.ipynb
db.todos = db.create(Todo) 
