"""Utility stuff like database connection and layout"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['db', 'post_tbl', 'thread_tbl', 'status_opts', 'Post', 'Thread', 'Todo']

# %% ../nbs/utils.ipynb 2
from fasthtml.common import *
from monsterui.all import *

# %% ../nbs/utils.ipynb 3
db = Database('productivity_app.db')

# %% ../nbs/utils.ipynb 7
@dataclass
class Post:
    id: str # Post Id (pid) is PK
    tid: int # Thread ID (tid)
    position: int # position in thread
    content: str # text content
    img_path: str = None # fpath to image is used
    username: str = "User" # For UI - no functional purpose
    handle: str = "@user" # For UI - no functional purpose
    created_at: str = "Just now" # For UI - no functional purpose
    modified_at: str = None # TODO: add mofified timestampe
        

# %% ../nbs/utils.ipynb 8
@dataclass
class Thread:
    id: str # tid
    name: str # human readable name
    user: str # user this is for, used for filtering down what is shown in UI
    created_on: str=None # TODO: Add created date for UI selection/sorting

# %% ../nbs/utils.ipynb 9
post_tbl = db.create(Post, 'posts')
thread_tbl = db.create(Thread, 'threads')

# %% ../nbs/utils.ipynb 11
status_opts = ("Todo", "In Progress", "Done", "Archived", "Someday", "Other")

# %% ../nbs/utils.ipynb 12
class Todo:
    title: str; id: int; updated_at: str; labels: str; repo_url: str; 
    html_url: str; repo_owner: str; repo_name: str; number: int;
    status: str 

# %% ../nbs/utils.ipynb 13
db.todos = db.create(Todo) 
